### ISSUE TITLE
Still work ?

### ISSUE THREAD

**Issue by Ucijunaedi** [Aadityajoshi151/Whatsapp-Group-Contacts-Exporter#1]
Hai, this apps still work ?

**Comment by Aadityajoshi151** [comment]
@Ucijunaedi As of now, unfortunately, it is not working.
Whatsapp web is very dynamic and picking up elements using selenium is being more difficult for me than I thought.
I haven't been able to resume this project because of my work and lack of free time. However, I will pick this again and try to finish it.
Any contributions are welcome.
I am sorry for inconvenience. 
Thank you.
